name = "botgroupchat"
main = "index.ts"
compatibility_date = "2026-05-19"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "bgkv"
id = "122e7b879d21493aab6eaa23956b8ed8"
preview_id = "122e7b879d21493aab6eaa23956b8ed8"  # 本地开发环境使用

[[d1_databases]]
binding = "bgdb" # available in your Worker on env.DB
database_name = "friends"
database_id = "f68e9fa5-4aea-45db-9516-2d7052e936fa"
